---
vertices:
- gid: root
  label: Query

- gid: Aliquot
  label: Object
  data:
    fields:
      AnalyteType: String
      Concentration: Float
      ExternalID: String
      ID: String
      SampleID: String
      ShipmentDestination: String
      ShipmentOrigin: String
      UUID: String
      Volume: Float

- gid: Demographic
  label: Object
  data:
    fields:
      Ethnicity: String
      ExternalID: String
      Gender: String
      ID: String
      ParticipantID: String
      Race: String
      UUID: String

- gid: Diagnosis
  label: Object
  data:
    fields:
      Diagnosis: String
      DiagnosisCategory: String
      ExternalID: String
      ID: String
      ParticipantID: String
      TumorLocation: String
      UUID: String

- gid: FamilyRelationship
  label: Object
  data:
    fields:
      ID: String
      ParticipantID: String
      ParticipantToRelativeRelation: String
      RelativeID: String
      RelativeToParticipantRelation: String
      UUID: String

- gid: GenomicFile
  label: Object
  data:
    fields:
      ControlledAccess: Boolean
      DataType: String
      FileFormat: String
      FileName: String
      FileUrl: String
      ID: String
      MD5sum: String
      SequencingExperimentID: String
      UUID: String

- gid: Investigator
  label: Object
  data:
    fields:
      ID: String
      Institution: String
      Name: String
      UUID: String

- gid: Outcome
  label: Object
  data:
    fields:
      DiseaseRelated: Boolean
      ID: String
      ParticipantID: String
      UUID: String
      VitalStatus: String

- gid: Participant
  label: Object
  data:
    fields:
      ConsentType: String
      ExternalID: String
      FamilyID: String
      ID: String
      IsProband: Boolean
      StudyID: String
      UUID: String

- gid: Phenotype
  label: Object
  data:
    fields:
      HpoID: String
      ID: String
      Observed: String
      ParticipantID: String
      Phenotype: String
      UUID: String

- gid: Sample
  label: Object
  data:
    fields:
      AnatomicalSite: String
      Composition: String
      ExternalID: String
      ID: String
      ParticipantID: String
      TissueType: String
      TumorDescriptor: String
      UUID: String

- gid: SequencingExperiment
  label: Object
  data:
    fields:
      AliquotID: String
      Center: String
      ExperimentStrategy: String
      ExternalID: String
      ID: String
      InstrumentModel: String
      IsPairedEnd: Boolean
      LibraryName: String
      LibraryStrand: String
      MaxInsertSize: Float
      MeanDepth: Float
      MeanInsertSize: Float
      MeanReadLength: Float
      Platform: String
      TotalReads: Float
      UUID: String

- gid: Study
  label: Object
  data:
    fields:
      Attribution: String
      DataAccessAuthority: String
      ExternalID: String
      ID: String
      InvestigatorID: String
      Name: String
      UUID: String
      Version: String

- gid: StudyFile
  label: Object
  data:
    fields:
      FileName: String
      ID: String
      StudyID: String
      UUID: String

edges:

###################################
# Model to root query

- label: field
  from: root
  to: Study
  data:
    name: Study
    type: idQuery

- label: field
  from: root
  to: Study
  data:
    name: StudyIds
    type: idList

- label: field
  from: root
  to: Aliquot
  data:
    name: Aliquot
    type: idQuery

- label: field
  from: root
  to: Demographic
  data:
    name: Demographic
    type: idQuery

- label: field
  from: root
  to: Diagnosis
  data:
    name: Diagnosis
    type: idQuery

- label: field
  from: root
  to: FamilyRelationship
  data:
    name: FamilyRelationship
    type: idQuery

- label: field
  from: root
  to: GenomicFile
  data:
    name: GenomicFile
    type: idQuery

- label: field
  from: root
  to: Investigator
  data:
    name: Investigator
    type: idQuery

- label: field
  from: root
  to: Outcome
  data:
    name: Outcome
    type: idQuery

- label: field
  from: root
  to: Participant
  data:
    name: Participant
    type: idQuery

- label: field
  from: root
  to: Participant
  data:
    name: ParticipantIds
    type: idList

- label: field
  from: root
  to: Phenotype
  data:
    name: Phenotype
    type: idQuery

- label: field
  from: root
  to: Sample
  data:
    name: Sample
    type: idQuery

- label: field
  from: root
  to: SequencingExperiment
  data:
    name: SequencingExperiment
    type: idQuery

- label: field
  from: root
  to: StudyFile
  data:
    name: StudyFile
    type: idQuery

- label: field
  from: root
  to: Workflow
  data:
    name: Workflow
    type: idQuery

- label: field
  from: root
  to: Workflow
  data:
    name: WorkflowIds
    type: idList


###################################
# Model to model relationships

- label: field
  from: Workflow
  to: WorkflowRun
  data:
    name: WorkflowRun
    label: WorkflowRun to Workflow

- label: field
  from: WorkflowRun
  to: StepRun
  data:
    name: StepRun
    label: StepRun to WorkflowRun

- label: field
  from: StepRun
  to: Task
  data:
    name: Task
    label: Task to StepRun

- label: field
  from: Workflow
  to: Step
  data:
    name: Step
    label: Step to Workflow

#Aliquot to Sample
- label: field
  from: Aliquot
  to: Sample
  data:
    name: Sample
    label: Aliquot to Sample

- label: field
  from: Sample
  to: Aliquot
  data:
    name: Aliquot
    label: Aliquot to Sample

#Demographic to Participant
- label: field
  from: Demographic
  to: Participant
  data:
    name: Participant
    label: Demographic to Participant

- label: field
  from: Participant
  to: Demographic
  data:
    name: Demographic
    label: Demographic to Participant

#Diagnosis to Participant
- label: field
  from: Diagnosis
  to: Participant
  data:
    name: Participant
    label: Diagnosis to Participant

- label: field
  from: Participant
  to: Diagnosis
  data:
    name: Diagnosis
    label: Diagnosis to Participant

#FamilyRelationship to Participant
- label: field
  from: FamilyRelationship
  to: Participant
  data:
    name: Participant
    label: FamilyRelationship to Participant

- label: field
  from: Participant
  to: FamilyRelationship
  data:
    name: FamilyRelationship
    label: FamilyRelationship to Participant

#FamilyRelationship to Relative
- label: field
  from: FamilyRelationship
  to: Participant
  data:
    name: Relative
    label: FamilyRelationship to Participant

- label: field
  from: Participant
  to: FamilyRelationship
  data:
    name: FamilyRelationship
    label: FamilyRelationship to Participant

#GenomicFile to SequencingExperiment
- label: field
  from: GenomicFile
  to: SequencingExperiment
  data:
    name: SequencingExperiment
    label: GenomicFile to SequencingExperiment

- label: field
  from: SequencingExperiment
  to: GenomicFile
  data:
    name: GenomicFile
    label: GenomicFile to SequencingExperiment

#Participant to Study
- label: field
  from: Study
  to: Participant
  data:
    name: Participant
    label: Participant to Study

- label: field
  from: Participant
  to: Study
  data:
    name: Study
    label: Participant to Study

#Phenotype to Participant
- label: field
  from: Phenotype
  to: Participant
  data:
    name: Participant
    label: Phenotype to Participant

- label: field
  from: Participant
  to: Phenotype
  data:
    name: Phenotype
    label: Phenotype to Participant

#Sample to Participant
- label: field
  from: Sample
  to: Participant
  data:
    name: Participant
    label: Sample to Participant

- label: field
  from: Participant
  to: Sample
  data:
    name: Sample
    label: Sample to Participant

#SequencingExperiment to Aliquot
- label: field
  from: SequencingExperiment
  to: Aliquot
  data:
    name: Aliquot
    label: SequencingExperiment to Aliquot

- label: field
  from: Aliquot
  to: SequencingExperiment
  data:
    name: SequencingExperiment
    label: SequencingExperiment to Aliquot

#Study to Investigator
- label: field
  from: Study
  to: Investigator
  data:
    name: Investigator
    label: Study to Investigator

- label: field
  from: Investigator
  to: Study
  data:
    name: Study
    label: Study to Investigator

#StudyFile to Study
- label: field
  from: StudyFile
  to: Study
  data:
    name: Study
    label: StudyFile to Study

- label: field
  from: Study
  to: StudyFile
  data:
    name: StudyFile
    label: StudyFile to Study
